import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class DataListService {
  private list = [
    {
      login: 'mojombo',
      id: 1,
      node_id: 'MDQ6VXNlcjE=',
      avatar_url: 'https://avatars.githubusercontent.com/u/1?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/mojombo',
      html_url: 'https://github.com/mojombo',
      followers_url: 'https://api.github.com/users/mojombo/followers',
      following_url:
        'https://api.github.com/users/mojombo/following{/other_user}',
      gists_url: 'https://api.github.com/users/mojombo/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/mojombo/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/mojombo/subscriptions',
      organizations_url: 'https://api.github.com/users/mojombo/orgs',
      repos_url: 'https://api.github.com/users/mojombo/repos',
      events_url: 'https://api.github.com/users/mojombo/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/mojombo/received_events',
      type: 'User',
      site_admin: false,
      name: 'Tom Preston-Werner',
      company: '@chatterbugapp, @redwoodjs, @preston-werner-ventures ',
      blog: 'http://tom.preston-werner.com',
      location: 'San Francisco',
      email: null,
      hireable: null,
      bio: null,
      twitter_username: 'mojombo',
      public_repos: 66,
      public_gists: 62,
      followers: 23656,
      following: 11,
      created_at: '2007-10-20T05:24:19Z',
      updated_at: '2023-09-18T18:49:27Z',
    },
    {
      login: 'defunkt',
      id: 2,
      node_id: 'MDQ6VXNlcjI=',
      avatar_url: 'https://avatars.githubusercontent.com/u/2?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/defunkt',
      html_url: 'https://github.com/defunkt',
      followers_url: 'https://api.github.com/users/defunkt/followers',
      following_url:
        'https://api.github.com/users/defunkt/following{/other_user}',
      gists_url: 'https://api.github.com/users/defunkt/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/defunkt/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/defunkt/subscriptions',
      organizations_url: 'https://api.github.com/users/defunkt/orgs',
      repos_url: 'https://api.github.com/users/defunkt/repos',
      events_url: 'https://api.github.com/users/defunkt/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/defunkt/received_events',
      type: 'User',
      site_admin: false,
      name: 'Chris Wanstrath',
      company: null,
      blog: 'http://chriswanstrath.com/',
      location: null,
      email: null,
      hireable: null,
      bio: '🍔',
      twitter_username: null,
      public_repos: 107,
      public_gists: 273,
      followers: 21736,
      following: 214,
      created_at: '2007-10-20T05:24:19Z',
      updated_at: '2023-09-29T23:19:40Z',
    },
    {
      login: 'pjhyett',
      id: 3,
      node_id: 'MDQ6VXNlcjM=',
      avatar_url: 'https://avatars.githubusercontent.com/u/3?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/pjhyett',
      html_url: 'https://github.com/pjhyett',
      followers_url: 'https://api.github.com/users/pjhyett/followers',
      following_url:
        'https://api.github.com/users/pjhyett/following{/other_user}',
      gists_url: 'https://api.github.com/users/pjhyett/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/pjhyett/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/pjhyett/subscriptions',
      organizations_url: 'https://api.github.com/users/pjhyett/orgs',
      repos_url: 'https://api.github.com/users/pjhyett/repos',
      events_url: 'https://api.github.com/users/pjhyett/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/pjhyett/received_events',
      type: 'User',
      site_admin: false,
      name: 'PJ Hyett',
      company: 'GitHub, Inc.',
      blog: 'https://hyett.com',
      location: 'San Francisco',
      email: null,
      hireable: null,
      bio: null,
      twitter_username: null,
      public_repos: 8,
      public_gists: 21,
      followers: 8260,
      following: 30,
      created_at: '2008-01-07T17:54:22Z',
      updated_at: '2023-03-20T06:54:31Z',
    },
    {
      login: 'wycats',
      id: 4,
      node_id: 'MDQ6VXNlcjQ=',
      avatar_url: 'https://avatars.githubusercontent.com/u/4?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/wycats',
      html_url: 'https://github.com/wycats',
      followers_url: 'https://api.github.com/users/wycats/followers',
      following_url:
        'https://api.github.com/users/wycats/following{/other_user}',
      gists_url: 'https://api.github.com/users/wycats/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/wycats/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/wycats/subscriptions',
      organizations_url: 'https://api.github.com/users/wycats/orgs',
      repos_url: 'https://api.github.com/users/wycats/repos',
      events_url: 'https://api.github.com/users/wycats/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/wycats/received_events',
      type: 'User',
      site_admin: false,
      name: 'Yehuda Katz',
      company: '@tildeio ',
      blog: 'http://yehudakatz.com',
      location: 'Portland, OR',
      email: null,
      hireable: null,
      bio: null,
      twitter_username: 'wycats',
      public_repos: 282,
      public_gists: 761,
      followers: 10148,
      following: 13,
      created_at: '2008-01-12T05:38:33Z',
      updated_at: '2023-10-12T23:54:10Z',
    },
    {
      login: 'ezmobius',
      id: 5,
      node_id: 'MDQ6VXNlcjU=',
      avatar_url: 'https://avatars.githubusercontent.com/u/5?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/ezmobius',
      html_url: 'https://github.com/ezmobius',
      followers_url: 'https://api.github.com/users/ezmobius/followers',
      following_url:
        'https://api.github.com/users/ezmobius/following{/other_user}',
      gists_url: 'https://api.github.com/users/ezmobius/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/ezmobius/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/ezmobius/subscriptions',
      organizations_url: 'https://api.github.com/users/ezmobius/orgs',
      repos_url: 'https://api.github.com/users/ezmobius/repos',
      events_url: 'https://api.github.com/users/ezmobius/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/ezmobius/received_events',
      type: 'User',
      site_admin: false,
      name: 'Ezra Zygmuntowicz',
      company: 'Stuffstr PBC',
      blog: 'http://stuffstr.com',
      location: 'In the NW',
      email: null,
      hireable: null,
      bio: null,
      twitter_username: null,
      public_repos: 22,
      public_gists: 106,
      followers: 545,
      following: 13,
      created_at: '2008-01-12T07:51:46Z',
      updated_at: '2023-09-22T11:24:10Z',
    },
    {
      login: 'ivey',
      id: 6,
      node_id: 'MDQ6VXNlcjY=',
      avatar_url: 'https://avatars.githubusercontent.com/u/6?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/ivey',
      html_url: 'https://github.com/ivey',
      followers_url: 'https://api.github.com/users/ivey/followers',
      following_url: 'https://api.github.com/users/ivey/following{/other_user}',
      gists_url: 'https://api.github.com/users/ivey/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/ivey/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/ivey/subscriptions',
      organizations_url: 'https://api.github.com/users/ivey/orgs',
      repos_url: 'https://api.github.com/users/ivey/repos',
      events_url: 'https://api.github.com/users/ivey/events{/privacy}',
      received_events_url: 'https://api.github.com/users/ivey/received_events',
      type: 'User',
      site_admin: false,
      name: 'Michael D. Ivey',
      company: '@RiotGames ',
      blog: 'https://gweezlebur.com',
      location: 'Tuscumbia, AL',
      email: null,
      hireable: null,
      bio: null,
      twitter_username: 'ivey',
      public_repos: 37,
      public_gists: 80,
      followers: 142,
      following: 3,
      created_at: '2008-01-12T15:15:00Z',
      updated_at: '2023-09-22T11:24:10Z',
    },
    {
      login: 'evanphx',
      id: 7,
      node_id: 'MDQ6VXNlcjc=',
      avatar_url: 'https://avatars.githubusercontent.com/u/7?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/evanphx',
      html_url: 'https://github.com/evanphx',
      followers_url: 'https://api.github.com/users/evanphx/followers',
      following_url:
        'https://api.github.com/users/evanphx/following{/other_user}',
      gists_url: 'https://api.github.com/users/evanphx/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/evanphx/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/evanphx/subscriptions',
      organizations_url: 'https://api.github.com/users/evanphx/orgs',
      repos_url: 'https://api.github.com/users/evanphx/repos',
      events_url: 'https://api.github.com/users/evanphx/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/evanphx/received_events',
      type: 'User',
      site_admin: false,
      name: 'Evan Phoenix',
      company: '@hashicorp ',
      blog: 'https://evanphx.dev',
      location: 'Los Angeles, CA',
      email: null,
      hireable: null,
      bio: null,
      twitter_username: 'evanphx',
      public_repos: 182,
      public_gists: 445,
      followers: 1575,
      following: 7,
      created_at: '2008-01-12T16:46:24Z',
      updated_at: '2023-09-18T03:52:40Z',
    },
    {
      login: 'vanpelt',
      id: 17,
      node_id: 'MDQ6VXNlcjE3',
      avatar_url: 'https://avatars.githubusercontent.com/u/17?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/vanpelt',
      html_url: 'https://github.com/vanpelt',
      followers_url: 'https://api.github.com/users/vanpelt/followers',
      following_url:
        'https://api.github.com/users/vanpelt/following{/other_user}',
      gists_url: 'https://api.github.com/users/vanpelt/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/vanpelt/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/vanpelt/subscriptions',
      organizations_url: 'https://api.github.com/users/vanpelt/orgs',
      repos_url: 'https://api.github.com/users/vanpelt/repos',
      events_url: 'https://api.github.com/users/vanpelt/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/vanpelt/received_events',
      type: 'User',
      site_admin: false,
      name: 'Chris Van Pelt',
      company: 'crowdflower.com',
      blog: 'wandb.com',
      location: 'San Francisco',
      email: null,
      hireable: null,
      bio: null,
      twitter_username: null,
      public_repos: 58,
      public_gists: 50,
      followers: 218,
      following: 20,
      created_at: '2008-01-13T05:57:18Z',
      updated_at: '2023-10-09T21:12:41Z',
    },
    {
      login: 'wayneeseguin',
      id: 18,
      node_id: 'MDQ6VXNlcjE4',
      avatar_url: 'https://avatars.githubusercontent.com/u/18?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/wayneeseguin',
      html_url: 'https://github.com/wayneeseguin',
      followers_url: 'https://api.github.com/users/wayneeseguin/followers',
      following_url:
        'https://api.github.com/users/wayneeseguin/following{/other_user}',
      gists_url: 'https://api.github.com/users/wayneeseguin/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/wayneeseguin/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/wayneeseguin/subscriptions',
      organizations_url: 'https://api.github.com/users/wayneeseguin/orgs',
      repos_url: 'https://api.github.com/users/wayneeseguin/repos',
      events_url: 'https://api.github.com/users/wayneeseguin/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/wayneeseguin/received_events',
      type: 'User',
      site_admin: false,
      name: 'Wayne E Seguin',
      company: 'FiveTwenty, Inc.',
      blog: '',
      location: 'Buffalo, NY',
      email: null,
      hireable: null,
      bio: 'OSS Creator, Contributor, & Maintainer.',
      twitter_username: 'wayneeseguin',
      public_repos: 104,
      public_gists: 95,
      followers: 729,
      following: 19,
      created_at: '2008-01-13T06:02:21Z',
      updated_at: '2023-10-13T16:33:45Z',
    },
    {
      login: 'brynary',
      id: 19,
      node_id: 'MDQ6VXNlcjE5',
      avatar_url: 'https://avatars.githubusercontent.com/u/19?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/brynary',
      html_url: 'https://github.com/brynary',
      followers_url: 'https://api.github.com/users/brynary/followers',
      following_url:
        'https://api.github.com/users/brynary/following{/other_user}',
      gists_url: 'https://api.github.com/users/brynary/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/brynary/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/brynary/subscriptions',
      organizations_url: 'https://api.github.com/users/brynary/orgs',
      repos_url: 'https://api.github.com/users/brynary/repos',
      events_url: 'https://api.github.com/users/brynary/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/brynary/received_events',
      type: 'User',
      site_admin: false,
      name: 'Bryan Helmkamp',
      company: 'Code Climate',
      blog: 'http://codeclimate.com',
      location: 'New York City',
      email: null,
      hireable: null,
      bio: 'Co-founder and CEO, Code Climate',
      twitter_username: null,
      public_repos: 171,
      public_gists: 69,
      followers: 667,
      following: 29,
      created_at: '2008-01-13T10:19:47Z',
      updated_at: '2023-09-25T01:09:26Z',
    },
  ];

  public getUserDataService() {
    return this.list;
  }
}
